name: fitness_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/image1.png
    - lib/assets/image2.png
    - lib/assets/image3.png
    - lib/assets/logofb.svg
    - lib/assets/FITBODY.svg
    - lib/assets/icon1.svg
    - lib/assets/icon2.svg
    - lib/assets/icon3.svg
    - lib/assets/main-image.png
    - lib/assets/Arrow.svg
    - lib/assets/fingerprint_icon.svg
    - lib/assets/facebook_icon.svg
    - lib/assets/google_icon.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

    - family: LeagueSpartan
      fonts:
          - asset: lib/assets/fonts/LeagueSpartan-Regular.ttf
          - asset: lib/assets/fonts/LeagueSpartan-Bold.ttf
            weight: 700